language: node_js
node_js:
  - '6'
os:
  - osx
env:
  matrix:
    - TARGET_ARCH=x64
osx_image: xcode7.3
addons:
  apt:
    packages:
    - xvfb
before_install:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1440x900x24 > /dev/null 2>&1 &
cache:
  directories:
  - node_modules
install:
  - nvm install 6
  - npm install
  - npm prune
  - npm install -g bower
  - bower install --allow-root
  - bower prune
script:
  - npm test
before_deploy:
  - npm run dist-unsigned
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
  all_branches: true
  file_glob: true
  file: dist/mac/BrowserDispatcher-*
  api-key:
    secure: UiqdJtG+XMIIl0SghTk9j3apSlte8QIGikNHhcU7qaQ6cEhB1kfrc+HwY+j0QcbmPYkcYuQgS+t7ZrYuOx1EjqCtdjtHDkXaChz6zewHGpUu1m2EY2xjJVgiQVZLdxpe2VlKpKwoHP0j+sPMO9uuB56xnnFFhZvXUnK1kkCHmGfhOeaFUxMvbm+U6zlUG0OKzSKYMJoiRqnBCg8CmgDKP8eL4oZi90HcvSpJbuvyEqiOuewOlDE9m5nJ0KKJLXDYJIGsmZinRZNN4m+h8+aRdlyC1fEeYtBZOJgzGkRQIocNBzOR73nHGSGKjOl9gVCN705WBk5Fx+BFR50u8lyrWjeLZs1gYDcjQrOBhety1wM5HRcwJxWhSDqy+342FsVfXOQq9AxOBp6lgIw5/mZD8FxH296iyHuq23X53SYiH0QeUYwJ4Sg7uS5Y8e/BTOjCxeYAwUUsQPolxfC3AdlQcEFam6kKKjeNWFOrzdOLUrbZFpSbVoHO7BTAtXwb1Qh7VyYNG88r/gKNJl2wvxbHgpmAR8EP4/TpGf7phtGULHQ1ZlofK7DxNkEk8rnbOKBCdgtYCi60AdSkeUNanGAK2LsUcFr2lmWXGzBjHhuwpu2fGwDx1m4OPhwc6NY7x6QMi/EMsxC0J2gFRUr1IKWzX4fJvltlrrzVXTLPUXb2uCc=
